//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Human.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Human.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyệt đối KHÔNG chia sẻ mã xác thực (OTP) với bất kỳ ai trong ảnh
        ///bất kỳ công thức nào. Mã xác thực có hiệu lực trong 1 phút.
        /// </summary>
        public static string Absolutely_otp {
            get {
                return ResourceManager.GetString("Absolutely_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duyệt.
        /// </summary>
        public static string Accept_btn {
            get {
                return ResourceManager.GetString("Accept_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string Account_Number {
            get {
                return ResourceManager.GetString("Account_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm Conect account.
        /// </summary>
        public static string Account_team {
            get {
                return ResourceManager.GetString("Account_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hợp đồng lao động thất bại.
        /// </summary>
        public static string Add_contract_fail {
            get {
                return ResourceManager.GetString("Add_contract_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm hợp đồng thành công.
        /// </summary>
        public static string Add_contract_success {
            get {
                return ResourceManager.GetString("Add_contract_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin nhân viên.
        /// </summary>
        public static string Add_emp_info {
            get {
                return ResourceManager.GetString("Add_emp_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin nhân viên thất bại.
        /// </summary>
        public static string Add_emp_info_fail {
            get {
                return ResourceManager.GetString("Add_emp_info_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin nhân viên thành công.
        /// </summary>
        public static string Add_emp_info_success {
            get {
                return ResourceManager.GetString("Add_emp_info_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhân viên.
        /// </summary>
        public static string Add_employee {
            get {
                return ResourceManager.GetString("Add_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm phép.
        /// </summary>
        public static string Add_leave {
            get {
                return ResourceManager.GetString("Add_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string add_leave_day {
            get {
                return ResourceManager.GetString("add_leave_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string add_leave_from_day {
            get {
                return ResourceManager.GetString("add_leave_from_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lý do.
        /// </summary>
        public static string Add_leave_reason {
            get {
                return ResourceManager.GetString("Add_leave_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string add_leave_to_day {
            get {
                return ResourceManager.GetString("add_leave_to_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới phép thất bại.
        /// </summary>
        public static string Add_new_leave_failed {
            get {
                return ResourceManager.GetString("Add_new_leave_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới phép thành công.
        /// </summary>
        public static string Add_new_leave_successful {
            get {
                return ResourceManager.GetString("Add_new_leave_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm lịch sử lương thất bại.
        /// </summary>
        public static string Add_salary_history_fail {
            get {
                return ResourceManager.GetString("Add_salary_history_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm lịch sử lương thành công.
        /// </summary>
        public static string Add_salary_history_success {
            get {
                return ResourceManager.GetString("Add_salary_history_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm quá trình công tác thất bại.
        /// </summary>
        public static string Add_work_process_fail {
            get {
                return ResourceManager.GetString("Add_work_process_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm quá trình công tác thành công.
        /// </summary>
        public static string Add_work_process_success {
            get {
                return ResourceManager.GetString("Add_work_process_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt menu quản trị.
        /// </summary>
        public static string Admin_menu_settings {
            get {
                return ResourceManager.GetString("Admin_menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Admin_setting {
            get {
                return ResourceManager.GetString("Admin_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả phòng ban.
        /// </summary>
        public static string All_department {
            get {
                return ResourceManager.GetString("All_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả phép.
        /// </summary>
        public static string All_leave {
            get {
                return ResourceManager.GetString("All_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả ngành.
        /// </summary>
        public static string All_section {
            get {
                return ResourceManager.GetString("All_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả trạng thái.
        /// </summary>
        public static string All_status {
            get {
                return ResourceManager.GetString("All_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp thu ngân.
        /// </summary>
        public static string Allowance_cashier {
            get {
                return ResourceManager.GetString("Allowance_cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp nhà ở.
        /// </summary>
        public static string Allowance_house {
            get {
                return ResourceManager.GetString("Allowance_house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp công việc.
        /// </summary>
        public static string Allowance_job {
            get {
                return ResourceManager.GetString("Allowance_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp bữa ăn.
        /// </summary>
        public static string Allowance_meal {
            get {
                return ResourceManager.GetString("Allowance_meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp khác.
        /// </summary>
        public static string Allowance_other {
            get {
                return ResourceManager.GetString("Allowance_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp xăng.
        /// </summary>
        public static string Allowance_petrol {
            get {
                return ResourceManager.GetString("Allowance_petrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ cấp điện thoại.
        /// </summary>
        public static string Allowance_phone {
            get {
                return ResourceManager.GetString("Allowance_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng.
        /// </summary>
        public static string Bank_account {
            get {
                return ResourceManager.GetString("Bank_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        public static string Bank_code {
            get {
                return ResourceManager.GetString("Bank_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin ngân hàng.
        /// </summary>
        public static string Bank_Info {
            get {
                return ResourceManager.GetString("Bank_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng.
        /// </summary>
        public static string Bank_Name {
            get {
                return ResourceManager.GetString("Bank_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string btn_Edit {
            get {
                return ResourceManager.GetString("btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lại.
        /// </summary>
        public static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy phép thất bại.
        /// </summary>
        public static string Cancel_leave_failed {
            get {
                return ResourceManager.GetString("Cancel_leave_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy phép thành công.
        /// </summary>
        public static string Cancel_leave_successfully {
            get {
                return ResourceManager.GetString("Cancel_leave_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục tra cứu.
        /// </summary>
        public static string Category_lookup {
            get {
                return ResourceManager.GetString("Category_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng chỉ.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giới tính.
        /// </summary>
        public static string choose_gender {
            get {
                return ResourceManager.GetString("choose_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tất cả.
        /// </summary>
        public static string Clear_All {
            get {
                return ResourceManager.GetString("Clear_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Màu sắc.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số hợp đồng.
        /// </summary>
        public static string Contract_code {
            get {
                return ResourceManager.GetString("Contract_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hợp đồng.
        /// </summary>
        public static string Contract_info {
            get {
                return ResourceManager.GetString("Contract_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hợp đồng.
        /// </summary>
        public static string Contract_type {
            get {
                return ResourceManager.GetString("Contract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu bảng chấm công ngày.
        /// </summary>
        public static string Daily_timesheet_data {
            get {
                return ResourceManager.GetString("Daily_timesheet_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp.
        /// </summary>
        public static string Date_Issue {
            get {
                return ResourceManager.GetString("Date_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày vào.
        /// </summary>
        public static string Date_of_join {
            get {
                return ResourceManager.GetString("Date_of_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghỉ việc.
        /// </summary>
        public static string Day_off {
            get {
                return ResourceManager.GetString("Day_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền.
        /// </summary>
        public static string Decentralize {
            get {
                return ResourceManager.GetString("Decentralize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng cấp.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa lịch sử lương thất bại.
        /// </summary>
        public static string Del_salary_history_fail {
            get {
                return ResourceManager.GetString("Del_salary_history_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa lịch sử lương thành công.
        /// </summary>
        public static string Del_salary_history_success {
            get {
                return ResourceManager.GetString("Del_salary_history_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa quá trình công tác thất bại.
        /// </summary>
        public static string Del_work_process_fail {
            get {
                return ResourceManager.GetString("Del_work_process_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa quá trình công tác thành công.
        /// </summary>
        public static string Del_work_process_success {
            get {
                return ResourceManager.GetString("Del_work_process_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thất bại.
        /// </summary>
        public static string Delete_failed {
            get {
                return ResourceManager.GetString("Delete_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa phép thất bại.
        /// </summary>
        public static string Delete_leave_failed {
            get {
                return ResourceManager.GetString("Delete_leave_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa phép thành công.
        /// </summary>
        public static string Delete_leave_successfully {
            get {
                return ResourceManager.GetString("Delete_leave_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string Delete_successfully {
            get {
                return ResourceManager.GetString("Delete_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ chối.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý phòng ban.
        /// </summary>
        public static string Department_manager {
            get {
                return ResourceManager.GetString("Department_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        public static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa thông tin nhân viên.
        /// </summary>
        public static string Edit_emp_info {
            get {
                return ResourceManager.GetString("Edit_emp_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa quá trình công tác thất bại.
        /// </summary>
        public static string Edit_work_process_fail {
            get {
                return ResourceManager.GetString("Edit_work_process_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa quá trình công tác thành công.
        /// </summary>
        public static string Edit_work_process_success {
            get {
                return ResourceManager.GetString("Edit_work_process_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học vấn.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin học vấn.
        /// </summary>
        public static string Education_Info {
            get {
                return ResourceManager.GetString("Education_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hiệu lực.
        /// </summary>
        public static string Effective_date {
            get {
                return ResourceManager.GetString("Effective_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email, tên đăng nhập, số điện thoại.
        /// </summary>
        public static string email_user_name_phone_number {
            get {
                return ResourceManager.GetString("email_user name_phone number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        public static string Emp_info {
            get {
                return ResourceManager.GetString("Emp_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên yêu cầu hủy phép.
        /// </summary>
        public static string Emp_request_cancel_leave {
            get {
                return ResourceManager.GetString("Emp_request_cancel_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string Employee_code {
            get {
                return ResourceManager.GetString("Employee_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phép nhân viên.
        /// </summary>
        public static string Employee_list_leave {
            get {
                return ResourceManager.GetString("Employee_list_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã bật.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kết thúc.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng.
        /// </summary>
        public static string English_show {
            get {
                return ResourceManager.GetString("English_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi khi tải lên.
        /// </summary>
        public static string error_while_upload {
            get {
                return ResourceManager.GetString("error_while_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinh nghiệm.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày hết hạn.
        /// </summary>
        public static string Expiration_date {
            get {
                return ResourceManager.GetString("Expiration_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string Forgot_pass {
            get {
                return ResourceManager.GetString("Forgot_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chung.
        /// </summary>
        public static string General_info {
            get {
                return ResourceManager.GetString("General_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp quyền hạn thất bại.
        /// </summary>
        public static string Granted_permissions_failed {
            get {
                return ResourceManager.GetString("Granted_permissions_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp quyền hạn thành công.
        /// </summary>
        public static string Granted_permissions_success {
            get {
                return ResourceManager.GetString("Granted_permissions_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHYT.
        /// </summary>
        public static string Health_Insurance {
            get {
                return ResourceManager.GetString("Health_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phép năm.
        /// </summary>
        public static string Home_annual_leave {
            get {
                return ResourceManager.GetString("Home_annual_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết phép.
        /// </summary>
        public static string Home_detail_leave {
            get {
                return ResourceManager.GetString("Home_detail_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin chào.
        /// </summary>
        public static string Home_hello {
            get {
                return ResourceManager.GetString("Home_hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Còn lại.
        /// </summary>
        public static string Home_remain {
            get {
                return ResourceManager.GetString("Home_remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string Home_total {
            get {
                return ResourceManager.GetString("Home_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng.
        /// </summary>
        public static string Home_used {
            get {
                return ResourceManager.GetString("Home_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ.
        /// </summary>
        public static string ID_card {
            get {
                return ResourceManager.GetString("ID_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Số CCCD.
        /// </summary>
        public static string Identity_card {
            get {
                return ResourceManager.GetString("Identity_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mã số nhân viên.
        /// </summary>
        public static string Input_emp_code {
            get {
                return ResourceManager.GetString("Input_emp_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hiểm.
        /// </summary>
        public static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi cấp.
        /// </summary>
        public static string Issued_by {
            get {
                return ResourceManager.GetString("Issued_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công việc phải làm.
        /// </summary>
        public static string Job_to_do {
            get {
                return ResourceManager.GetString("Job_to_do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp đồng lao động.
        /// </summary>
        public static string Labor_contract {
            get {
                return ResourceManager.GetString("Labor_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phép.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên nghỉ phép.
        /// </summary>
        public static string Leave_employee {
            get {
                return ResourceManager.GetString("Leave_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phép.
        /// </summary>
        public static string Leave_list {
            get {
                return ResourceManager.GetString("Leave_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý phép.
        /// </summary>
        public static string Leave_managment {
            get {
                return ResourceManager.GetString("Leave_managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách yêu cầu duyệt phép.
        /// </summary>
        public static string Leave_request_list {
            get {
                return ResourceManager.GetString("Leave_request_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string Leavel_list_add_new {
            get {
                return ResourceManager.GetString("Leavel_list_add_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trình độ.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string ListEmployee {
            get {
                return ResourceManager.GetString("ListEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công thực tế.
        /// </summary>
        public static string Log_list {
            get {
                return ResourceManager.GetString("Log_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bằng OTP.
        /// </summary>
        public static string Login_with_OTP {
            get {
                return ResourceManager.GetString("Login_with_OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập bằng mật khẩu.
        /// </summary>
        public static string Login_with_password {
            get {
                return ResourceManager.GetString("Login_with_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật logo thành công.
        /// </summary>
        public static string Logo_update_success {
            get {
                return ResourceManager.GetString("Logo_update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu dữ liệu.
        /// </summary>
        public static string Look_up_data {
            get {
                return ResourceManager.GetString("Look_up_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu chấm công thực tế.
        /// </summary>
        public static string Look_up_timekeep {
            get {
                return ResourceManager.GetString("Look_up_timekeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý.
        /// </summary>
        public static string Managment {
            get {
                return ResourceManager.GetString("Managment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string Marital_Status {
            get {
                return ResourceManager.GetString("Marital_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng/năm.
        /// </summary>
        public static string Month_year {
            get {
                return ResourceManager.GetString("Month_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hoặc mã nhân viên.
        /// </summary>
        public static string Name_or_code {
            get {
                return ResourceManager.GetString("Name or code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kế tiếp.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string No_data_available {
            get {
                return ResourceManager.GetString("No_data_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có thông báo.
        /// </summary>
        public static string No_notification {
            get {
                return ResourceManager.GetString("No_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu hợp đồng VÔ THỜI HẠN thì sẽ không hiển thị ngày hết hạn của hợp đồng.
        /// </summary>
        public static string Note_contract {
            get {
                return ResourceManager.GetString("Note_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string Ok_btn {
            get {
                return ResourceManager.GetString("Ok_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã OTP hết hạn, vui lòng lấy mã mới.
        /// </summary>
        public static string OTP_code_expired_please_get_code {
            get {
                return ResourceManager.GetString("OTP_code_expired_please_get_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỳ lương.
        /// </summary>
        public static string Payroll {
            get {
                return ResourceManager.GetString("Payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang  chờ.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhân viên.
        /// </summary>
        public static string Personal_Info {
            get {
                return ResourceManager.GetString("Personal_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string Pit_No {
            get {
                return ResourceManager.GetString("Pit_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn đầy đủ thông tin.
        /// </summary>
        public static string Please_select_complete_info {
            get {
                return ResourceManager.GetString("Please_select_complete_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trước.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thử việc.
        /// </summary>
        public static string Probation {
            get {
                return ResourceManager.GetString("Probation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ nhân viên.
        /// </summary>
        public static string Profile_Emloyee {
            get {
                return ResourceManager.GetString("Profile_Emloyee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghỉ việc.
        /// </summary>
        public static string Quit_job {
            get {
                return ResourceManager.GetString("Quit_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bậc.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu hủy.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu phê duyệt không thành công.
        /// </summary>
        public static string Request_approval_fail {
            get {
                return ResourceManager.GetString("Request_approval_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu được phê duyệt thành công.
        /// </summary>
        public static string Request_approved_success {
            get {
                return ResourceManager.GetString("Request_approved_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu.
        /// </summary>
        public static string Request_btn {
            get {
                return ResourceManager.GetString("Request_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi yêu cầu thất bại.
        /// </summary>
        public static string Request_sent_failed {
            get {
                return ResourceManager.GetString("Request_sent_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu được gửi thành công.
        /// </summary>
        public static string Request_sent_successfully {
            get {
                return ResourceManager.GetString("Request_sent_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương cơ bản.
        /// </summary>
        public static string Salary_basic {
            get {
                return ResourceManager.GetString("Salary_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lương nhân viên.
        /// </summary>
        public static string Salary_employee {
            get {
                return ResourceManager.GetString("Salary_employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử lương.
        /// </summary>
        public static string Salary_history {
            get {
                return ResourceManager.GetString("Salary_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp bậc lương.
        /// </summary>
        public static string Salary_level {
            get {
                return ResourceManager.GetString("Salary_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểm tra.
        /// </summary>
        public static string Search_public {
            get {
                return ResourceManager.GetString("Search_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ phận.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực.
        /// </summary>
        public static string Security_code {
            get {
                return ResourceManager.GetString("Security_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng sử dụng mã xác thực sau cho tài khoản Conect.
        /// </summary>
        public static string security_for_account {
            get {
                return ResourceManager.GetString("security_for_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tất cả.
        /// </summary>
        public static string Select_all {
            get {
                return ResourceManager.GetString("Select_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn loại hợp đồng.
        /// </summary>
        public static string Select_contract_type {
            get {
                return ResourceManager.GetString("Select_contract_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn phòng ban.
        /// </summary>
        public static string Select_department {
            get {
                return ResourceManager.GetString("Select_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn nhân viên.
        /// </summary>
        public static string Select_emp {
            get {
                return ResourceManager.GetString("Select_emp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngôn ngữ.
        /// </summary>
        public static string Select_language {
            get {
                return ResourceManager.GetString("Select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tháng/năm.
        /// </summary>
        public static string Select_month_year {
            get {
                return ResourceManager.GetString("Select_month_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chức vụ.
        /// </summary>
        public static string Select_position {
            get {
                return ResourceManager.GetString("Select_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn bộ phận.
        /// </summary>
        public static string Select_section {
            get {
                return ResourceManager.GetString("Select_section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày kí.
        /// </summary>
        public static string Sign_day {
            get {
                return ResourceManager.GetString("Sign_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BHXH.
        /// </summary>
        public static string Social_Insurance {
            get {
                return ResourceManager.GetString("Social_Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh chuyên môn.
        /// </summary>
        public static string Specialize_title {
            get {
                return ResourceManager.GetString("Specialize_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string Tax_code {
            get {
                return ResourceManager.GetString("Tax_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ tạm trú.
        /// </summary>
        public static string Temporary_addres {
            get {
                return ResourceManager.GetString("Temporary_addres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên này chưa có hợp đồng.
        /// </summary>
        public static string This_emp_not_contract {
            get {
                return ResourceManager.GetString("This_emp_not_contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày nghỉ phép này đã được xác nhận.
        /// </summary>
        public static string This_leave_date_has_been_confirmed {
            get {
                return ResourceManager.GetString("This_leave_date_has_been_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng công tháng.
        /// </summary>
        public static string Time_sheet {
            get {
                return ResourceManager.GetString("Time_sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công hàng ngày.
        /// </summary>
        public static string Time_sheet_day {
            get {
                return ResourceManager.GetString("Time_sheet_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công ngày.
        /// </summary>
        public static string Timekeep_day {
            get {
                return ResourceManager.GetString("Timekeep_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấm công.
        /// </summary>
        public static string Timekeeping {
            get {
                return ResourceManager.GetString("Timekeeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng phép năm.
        /// </summary>
        public static string Total_annual_leave {
            get {
                return ResourceManager.GetString("Total_annual_leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày nghỉ trong tháng.
        /// </summary>
        public static string Total_leaves_in_month {
            get {
                return ResourceManager.GetString("Total_leaves_in_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày nghỉ trong năm.
        /// </summary>
        public static string Total_leaves_in_year {
            get {
                return ResourceManager.GetString("Total_leaves_in_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật ảnh đại diện thành công.
        /// </summary>
        public static string Update_avt_success {
            get {
                return ResourceManager.GetString("Update_avt_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hợp đồng thất bại.
        /// </summary>
        public static string Update_contract_fail {
            get {
                return ResourceManager.GetString("Update_contract_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hợp đồng thành công.
        /// </summary>
        public static string Update_contract_success {
            get {
                return ResourceManager.GetString("Update_contract_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Cập nhật thông tin nhân viên thất bại.
        /// </summary>
        public static string Update_emp_info_fail {
            get {
                return ResourceManager.GetString("Update_emp_info_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin nhân viên thành công.
        /// </summary>
        public static string Update_emp_info_success {
            get {
                return ResourceManager.GetString("Update_emp_info_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phép thất bại!.
        /// </summary>
        public static string Update_leave_failed {
            get {
                return ResourceManager.GetString("Update_leave_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phép thành công!.
        /// </summary>
        public static string Update_leave_successful {
            get {
                return ResourceManager.GetString("Update_leave_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật lịch sử lương thất bại.
        /// </summary>
        public static string Update_salary_history_fail {
            get {
                return ResourceManager.GetString("Update_salary_history_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật lịch sử lương thành công.
        /// </summary>
        public static string Update_salary_history_success {
            get {
                return ResourceManager.GetString("Update_salary_history_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string User_name {
            get {
                return ResourceManager.GetString("User_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vie.
        /// </summary>
        public static string Vietnamese_show {
            get {
                return ResourceManager.GetString("Vietnamese_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem tất cả thông báo.
        /// </summary>
        public static string View_all_Notifications {
            get {
                return ResourceManager.GetString("View_all_Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá trình công tác.
        /// </summary>
        public static string Working_process {
            get {
                return ResourceManager.GetString("Working_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi làm việc.
        /// </summary>
        public static string Working_site {
            get {
                return ResourceManager.GetString("Working_site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai tài khoản hoặc mật khẩu.
        /// </summary>
        public static string Wrong_account_or_password {
            get {
                return ResourceManager.GetString("Wrong_account_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai mật khẩu OTP, vui lòng nhập lại.
        /// </summary>
        public static string Wrong_OTP_password_please_re_enter {
            get {
                return ResourceManager.GetString("Wrong_OTP_password_please_re_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu sai, vui lòng nhập lại.
        /// </summary>
        public static string Wrong_pass_please_re_enter {
            get {
                return ResourceManager.GetString("Wrong_pass_please_re_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền hạn này.
        /// </summary>
        public static string You_not_have_this_right {
            get {
                return ResourceManager.GetString("You_not_have_this_right", resourceCulture);
            }
        }
    }
}
